// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_slug_ from "./routes/[slug].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $blog from "./routes/blog.tsx";
import * as $feed from "./routes/feed.ts";
import * as $index from "./routes/index.tsx";
import * as $CodeBlockToggle from "./islands/CodeBlockToggle.tsx";
import * as $LandingSketch from "./islands/LandingSketch.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[slug].tsx": $_slug_,
    "./routes/_404.tsx": $_404,
    "./routes/blog.tsx": $blog,
    "./routes/feed.ts": $feed,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CodeBlockToggle.tsx": $CodeBlockToggle,
    "./islands/LandingSketch.tsx": $LandingSketch,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
